### ISSUE TITLE
Would you be willing to transfer the package "nuclear"?

### ISSUE THREAD

**Issue by loic-sharma** [MikeLimaSierra/Nuclear.Net#20]
Hello! I am building [a .NET tool to bulk unlist NuGet packages](https://github.com/loic-sharma/nuclear). Ideally I would like to call this app "nuclear", a portmanteau of "NuGet" and "Clear", but I see you already have this name on nuget.org: http://nuget.org/packages/nuclear

Would you be willing to transfer ownership of this NuGet package ID to me? If so, here's how:

1. Navigate to your package's manage page: https://www.nuget.org/packages/nuclear/1.1.0/Manage
1. Open the `Owners` section
1. Set the `Username` field to [`loic-sharma`](https://www.nuget.org/profiles/loic-sharma)
1. Press the `Add` button

Please let me know if you have any questions or concerns. I'd be happy to have a call to clarify any concerns or to verify my identity!

**Comment by MikeLimaSierra** [comment]
Hi,this is a legacy package that isn't in use anymore and I'd be happy to transfer it to you. There is also the package nuclear.contracts that comes with it. I'd rather transfer both to you in one go since I have no use for either one.

**Comment by loic-sharma** [comment]
Sounds good! Let me know if you have any problems transferring the packages on nuget.org, I'd be happy to help out 😃

**Comment by MikeLimaSierra** [comment]
No problems, just lacking time. Will transfer the packages later today.

**Comment by MikeLimaSierra** [comment]
You have two ownership transfer requests pending. Good luck with your project. It looks very useful, and I'll keep an eye out for it.

**Comment by loic-sharma** [comment]
Thank @MikeLimaSierra! :)

**Comment by MikeLimaSierra** [comment]
Any time. Projects like yours should get all the support they need.
Also, this is a feature that I have been requesting for a while now, and I'm happy to be a part of it's evolution ;-)
